name: "Alexa List Import"
slug: alexa_list_import
description: "Importiert Alexa Einkaufslisten automatisch in Home Assistant"
version: "1.0.4"
startup: services
boot: auto
host_network: true

options:
  amazon_email: ""
  amazon_password: ""
  amazon_2fa: ""
  region: "de"
  webhook_url: ""
  interval: 180
  clear_after_import: true
  debug: false

schema:
  amazon_email: str
  amazon_password: password
  amazon_2fa: str
  region: str
  webhook_url: str
  interval: int
  clear_after_import: bool
  debug: bool

image: "local/alexa_list_import"
