name: "Alexa List Import"
version: "1.0.0"
slug: "alexa_list_import"
description: "Imports Alexa shopping list into Home Assistant via webhook."
arch:
  - amd64
  - aarch64
startup: application
boot: auto
options:
  amazon_email: ""
  amazon_password: ""
  amazon_2fa: ""
  region: "de"
  webhook_url: ""
  interval: 180
  clear_after_import: true
  debug: true
schema:
  amazon_email: str
  amazon_password: password
  amazon_2fa: str
  region: str
  webhook_url: str
  interval: int
  clear_after_import: bool
  debug: bool
