name: "Alexa List Import"
version: "1.1.0"
slug: "alexa_list_import"
description: "Imports Alexa shopping list into Home Assistant"
url: "https://github.com/teezenergy/ha-alexa-list-import"
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

build_from:
  amd64: "Dockerfile"
  aarch64: "Dockerfile"
  armv7: "Dockerfile"
  armhf: "Dockerfile"
  i386: "Dockerfile"

ports: {}
map: []
options: {}
schema: {}
