name: "Alexa List Import"
version: "1.0.4"
slug: "ha-alexa_list_import"
description: "Importiert die Alexa Einkaufsliste automatisch in Home Assistant"
startup: services
boot: auto
host_network: false

options:
  amazon_email: ""
  amazon_password: ""
  amazon_2fa: ""
  region: "de"
  webhook_url: ""
  interval: 180
  clear_after_import: true
  debug: false

schema:
  amazon_email: str
  amazon_password: password
  amazon_2fa: password
  region: str
  webhook_url: str
  interval: int
  clear_after_import: bool
  debug: bool
