name: "Alexa List Import"
version: "1.0.0"
slug: "alexa_list_import"
description: "Imports Alexa shopping list into Home Assistant"
url: "https://github.com/teezenergy/ha-alexa-list-import"

startup: services
boot: auto
init: false
stage: stable

arch:
  - amd64
  - aarch64
  - armv7

ports: {}
map: []
options: {}
schema: {}

image: null
